set(SRC_FILES
    App.cpp
    Button.cpp
    ChooseLevelScene.cpp
    Enemy.cpp
    Level1.cpp
    main.cpp
    SceneManager.cpp
    StartScene.cpp
    Tile.cpp
    TileSet.cpp
    Heart.cpp
    Money.cpp
    Level.cpp
    Guard.cpp
    Swordsman.cpp
    Mage.cpp
    Musketeer.cpp
    Dragon.cpp
    ReadMap.cpp
    ReadEnemy.cpp
    Market.cpp
    TutorialScene.cpp
)

set(INCLUDE_FILES
    App.hpp
    Button.hpp
    Ui.hpp
    ChooseLevelScene.hpp
    Enemy.hpp
    Level.hpp
    SceneManager.hpp
    StartScene.hpp
    Tile.hpp
    TileSet.hpp
    Heart.hpp
    Money.hpp
    Guard.hpp
    Swordsman.hpp
    Mage.hpp
    Musketeer.hpp
    Dragon.hpp
    ReadMap.hpp
    ReadEnemy.hpp
    Market.hpp
    TutorialScene.hpp
)

set(TEST_FILES
)
